print()
print("Podaj wagę w kilogramach: \n")
waga = input()
print()
print("Podaj wzrost w metrach: \n")
wzrost = input()
print()
BMI = (float(waga)) / (float(wzrost)**2)
print("Twoje BMI wynosi: \n\n" + str(BMI))
print()
input("wciśnij ENTER żeby zamknąć okno")