print()
print("Witaj w świecie Pythona! :-) Jestem Twoim ulubionym botem!")
print()
input("Proszę, naciśnij ENTER aby przejść dalej.")
print()
print("Marzę, żeby Cię lepiej poznać. Proszę, odpowiedz na kilka pytań.")
print()
print ("Napisz, jak masz na imię i naciśnij ENTER:\n")
pobrany_napis1 = input()
print()
input("Dziękuję za odpowiedź. To moje ulubione imię :-) \n\nPonownie naciśnij ENTER, żeby przejść dalej.")
print()
print ("Teraz zdradź mi swoje nazwisko i pamiętaj, by wcisnąć ENTER, bo bez tego nic się nie wydarzy :-)\n")
pobrany_napis2 = input()
print()
input("Ooo, wspaniale! Takie nazwisko można nosić z dumą. \n\nProszę naciśnij ENTER, żeby przejść do ostatniego pytania.")
print()
print("Przy tym pytaniu niektórzy wymiękają, ale przecież nie Ty!\n\nNo to siup: Ile masz lat?\n\nPo podaniu wieku naciśnij ENTER\n")
pobrany_napis3 = input()
print()
input("Jesteś więc w kwiecie wieku! \n\nA skoro tak, to żwawo naciśnij ENTER, abyśmy zaczęli wspólną przygodę. \n\nJesteś super i razem stworzymy super drużynę.")
print()
print()
print ("ALBO JEDNAK SPIERDALAJ " + pobrany_napis1 + " " + pobrany_napis2 + "!!! \n\nCO ZA ZJEBANE NAZWISKO, A IMIĘ TAKIE CHUJOWE JAK TY. \n\nHAHAHA, " + pobrany_napis3 + " - SERIO TYLE MASZ LAT? JA JEBIE, ZAŁAMKA. \n\nŻE TEŻ TAKIE ŚMIECIE ZAWSZE MI SIĘ TRAFIAJĄ KURWA \n\nWYPIERDALAJ I NIE PRÓBUJ PISAĆ NA MNIE SKARG BO PRZYJDĘ I CI NAPIERDOLĘ ZJEBIE!")
print()
input ("NACIŚNIJ KURWA ENTER!")